# Generated by Django 4.2 on 2023-04-26 17:38

from django.db import migrations, models
import django.db.models.deletion
import studentApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepad',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentApp.project', verbose_name='project'),
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=studentApp.models.get_whiteboard_file_name)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentApp.project', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=studentApp.models.get_voice_memo_file_name)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.project', verbose_name='project')),
            ],
        ),
    ]
