# Generated by Django 4.2 on 2023-05-21 06:34

from django.db import migrations, models
import studentApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_alter_whiteboard_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoiceMemo',
            new_name='FileUploads',
        ),
        migrations.AlterField(
            model_name='whiteboard',
            name='file',
            field=models.ImageField(max_length=200, storage=studentApp.models.OverwriteStorage(), upload_to=studentApp.models.get_whiteboard_file_name),
        ),
    ]
